destination_admin_groups:
  FAKE-DESTINATION-LIBRARY: ['FAKE-DESTINATION-LIBRARY-TEST-LDAP-GROUP']

stanford_ips:
  singletons:
    - '172.1.1.1'

token_encrypt:
  secret: 'cphNKBJUCUlDeekeQGTmPkinkxAkJKxDsfHailJrKKIzxkSRFHbarXxjYRMdkyKW'
  salt: 'dGcTBhXrQjsvQkbDQCkAIdogYjzOiIQpjToNLjqyzslKShfTvxIJHmMZhzdNjOqtDZKtxutyHBZmNHKOcGMfHzxwCFeOTBeEHYHNedtrmdfLzHMTRSDJCRMURaAjRrDq'

mailer_host: 'example.com'

sul_illiad: 'https://illiad-test/'
illiad_email_address: 'illiad-test@stanford.edu'

background_jobs:
  enabled: false

features:
  hold_recall_service: true
  scan_service: true
